<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<wsdl:definitions xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://www.example.org/ServicioRequisitos/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="ServicioRequisitos" targetNamespace="http://www.example.org/ServicioRequisitos/">
  <wsdl:types>
    <xsd:schema targetNamespace="http://www.example.org/ServicioRequisitos/">
      <xsd:element name="ComprobarRequisitos">
        <xsd:complexType>
          <xsd:sequence>
          	<xsd:element name="correo" type="xsd:string" maxOccurs="1" minOccurs="1"/>
          	<xsd:element name="certificados" type="xsd:string" maxOccurs="unbounded" minOccurs="0"></xsd:element>
          </xsd:sequence>
        </xsd:complexType>
      </xsd:element>
      <xsd:element name="ComprobarRequisitosResponse">
        <xsd:complexType>
          <xsd:sequence>
          	<xsd:element name="ok" type="xsd:boolean" maxOccurs="1" minOccurs="1"/>
          	<xsd:element name="mensaje" type="xsd:string" maxOccurs="1" minOccurs="0"></xsd:element>
          </xsd:sequence>
        </xsd:complexType>
      </xsd:element>
    </xsd:schema>
  </wsdl:types>
  <wsdl:message name="ComprobarRequisitosRequest">
    <wsdl:part element="tns:ComprobarRequisitos" name="parameters"/>
  </wsdl:message>
  <wsdl:message name="ComprobarRequisitosResponse">
    <wsdl:part element="tns:ComprobarRequisitosResponse" name="parameters"/>
  </wsdl:message>
  <wsdl:portType name="ServicioRequisitos">
    <wsdl:operation name="ComprobarRequisitos">
      <wsdl:input message="tns:ComprobarRequisitosRequest"/>
      <wsdl:output message="tns:ComprobarRequisitosResponse"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="ServicioRequisitosSOAP" type="tns:ServicioRequisitos">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="ComprobarRequisitos">
      <soap:operation soapAction="http://www.example.org/ServicioRequisitos/ComprobarRequisitos"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="ServicioRequisitos">
    <wsdl:port binding="tns:ServicioRequisitosSOAP" name="ServicioRequisitosSOAP">
      <soap:address location="http://www.example.org/"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
